# Generated by Django 4.1.5 on 2023-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_website_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "brand",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
